# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   # annotations:
#   #   kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose-otel.yml convert -c
#   #   kompose.version: 1.28.0 (c4137012e)
#   # creationTimestamp: null
#   # labels:
#   #   io.kompose.service: grafana
#   name: grafana
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       io.kompose.service: grafana
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       # annotations:
#       #   kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose-otel.yml convert -c
#       #   kompose.version: 1.28.0 (c4137012e)
#       # creationTimestamp: null
#       # labels:
#       #   io.kompose.network/intro-to-mlt-default: "true"
#       #   io.kompose.service: grafana
#     spec:
#       containers:
#         - env:
#             - name: GF_AUTH_ANONYMOUS_ENABLED
#               value: "true"
#             - name: GF_AUTH_ANONYMOUS_ORG_ROLE
#               value: Admin
#             - name: GF_AUTH_DISABLE_LOGIN_FORM
#               value: "true"
#             - name: GF_FEATURE_TOGGLES_ENABLE
#               value: flameGraph topnav
#           image: grafana/grafana:9.4.7
#           name: grafana
#           ports:
#             - containerPort: 3000
#           resources: {}
#           volumeMounts:
#             - mountPath: /var/lib/grafana/dashboards
#               name: grafana-claim0
#             - mountPath: /etc/grafana/provisioning
#               name: grafana-claim1
#       restartPolicy: Always
#       volumes:
#         - name: grafana-claim0
#           persistentVolumeClaim:
#             claimName: grafana-claim0
              # configMap:
              #   name: grafana-conf-file
              #   items:
              #     - key: dashboards.json
              #       # path: dashboards.json
#         - name: grafana-claim1
#           persistentVolumeClaim:
#             claimName: grafana-claim1
              # configMap:
              #   name: grfana-conf-file
              #   items:
              #     - key: datasources.yaml
              #       # path: datasources.yaml
# status: {}
