apiVersion: apps/v1
kind: Deployment
metadata:
  # annotations:
  #   kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose-otel.yml convert -c
  #   kompose.version: 1.28.0 (c4137012e)
  # creationTimestamp: null
  # labels:
  #   io.kompose.service: loki
  name: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: loki
  strategy: {}
  template:
    metadata:
      # annotations:
      #   kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose-otel.yml convert -c
      #   kompose.version: 1.28.0 (c4137012e)
      # creationTimestamp: null
      # labels:
      #   io.kompose.network/intro-to-mlt-default: "true"
      #   io.kompose.service: loki
    spec:
      containers:
        - image: grafana/loki:2.8.0
          name: loki
          ports:
            - containerPort: 3100
          resources: {}
      restartPolicy: Always
status: {}
