# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   annotations:
#     kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose-otel.yml convert -c
#     kompose.version: 1.28.0 (c4137012e)
#   creationTimestamp: null
#   labels:
#     io.kompose.service: mimir
#   name: mimir
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       io.kompose.service: mimir
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       annotations:
#         kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose-otel.yml convert -c
#         kompose.version: 1.28.0 (c4137012e)
#       creationTimestamp: null
#       labels:
#         io.kompose.network/intro-to-mlt-default: "true"
#         io.kompose.service: mimir
#     spec:
#       containers:
#         - args:
#             - -config.file=/etc/mimir.yaml
#           image: grafana/mimir:2.7.1
#           name: mimir
#           ports:
#             - containerPort: 9009
#           resources: {}
#           volumeMounts:
#             - name: mimir-conf
#               mountPath: /etc/
#       restartPolicy: Always
#       volumes:
#         - name: mimir-claim0
#           persistentVolumeClaim:
#             claimName: mimir-claim0
#           configMap:
#             name: mimir-config-file
# status: {}
