apiVersion: v1
kind: Service
metadata:
  # annotations:
  #   kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose-otel.yml convert -c
  #   kompose.version: 1.28.0 (c4137012e)
  # creationTimestamp: null
  # labels:
  #   io.kompose.service: mimir
  name: mimir
spec:
  ports:
    - name: "9009"
      port: 9009
      targetPort: 9009
  selector:
    io.kompose.service: mimir
status:
  loadBalancer: {}
