apiVersion: v1
kind: Service
metadata:
  # annotations:
  #   kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose-otel.yml convert -c
  #   kompose.version: 1.28.0 (c4137012e)
  # creationTimestamp: null
  # labels:
  #   io.kompose.service: opentelemetry-collector
  name: opentelemetry-collector
spec:
  ports:
    - name: "12347"
      port: 12347
      targetPort: 12345
    - name: "12348"
      port: 12348
      targetPort: 12348
    - name: "6832"
      port: 6832
      targetPort: 6832
    - name: "55679"
      port: 55679
      targetPort: 55679
  selector:
    io.kompose.service: opentelemetry-collector
status:
  loadBalancer: {}
