apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose-otel.yml convert -c
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: opentelemetry-collector
  name: opentelemetry-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opentelemetry-collector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose-otel.yml convert -c
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/intro-to-mlt-default: "true"
        io.kompose.service: opentelemetry-collector
    spec:
      containers:
        - args:
            - --config=/etc/otel-collector-config.yml
          image: otel/opentelemetry-collector-contrib
          name: opentelemetry-collector
          ports:
            - containerPort: 12345
            - containerPort: 12348
            - containerPort: 6832
            - containerPort: 55679
          resources: {}
          volumeMounts:
            - mountPath: /etc/otel-collector-config.yml
              name: opentelemetry-collector-claim0
      restartPolicy: Always
      volumes:
        - name: opentelemetry-collector-claim0
          persistentVolumeClaim:
            claimName: opentelemetry-collector-claim0
status: {}
