# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: tempo-conf-file
#   lables: 
#     app: tempo
# data:
#   tempo.yaml: |- 
#     {{ .Files.Get "tempo/tempo.yaml" | indent 4 }} 
#    #{{ (.Files.Glob "mimir/mimir.yaml").AsConfig | indent 2 }}