apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose-otel.yml convert -c
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: tempo
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tempo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file docker-compose-otel.yml convert -c
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/intro-to-mlt-default: "true"
        io.kompose.service: tempo
    spec:
      containers:
        - args:
            - -config.file=/etc/tempo.yaml
          image: grafana/tempo:2.0.1
          name: tempo
          ports:
            - containerPort: 3200
            - containerPort: 4317
            - containerPort: 55680
            - containerPort: 55681
            - containerPort: 14250
          resources: {}
          volumeMounts:
            - mountPath: /etc/tempo.yaml
              name: tempo-claim0
      restartPolicy: Always
      volumes:
        - name: tempo-claim0
          persistentVolumeClaim:
            claimName: tempo-claim0
status: {}
